In [7]:
import pandas as pd

# df = dataframe = tabela
vendas_df = pd.read_csv("Vendas_Chocolate.csv", sep=";")
display(vendas_df)

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas,Data de Hoje
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,04/01/2022,"$5,320.00",180.0,03/02/2026
1,Vanderlei Teixeira,Índia,NaN,01/08/2022,"$7,896.00",94.0,NaN
2,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,07/07/2022,"$4,501.00",91.0,NaN
3,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,27/04/2022,"$12,726.00",342.0,NaN
4,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,24/02/2022,"$13,685.00",184.0,NaN
...,...,...,...,...,...,...,...
3277,Karina Machado,Austrália,Especiais Apimentados Finos,17/05/2024,"$5,303.58",354.0,NaN
3278,João Rocha,EUA,Chocolate Branco,07/06/2024,"$7,339.32",121.0,NaN
3279,Célio Bonfim,Canadá,Xarope de Chocolate Orgânico,26/07/2024,$616.09,238.0,NaN
3280,Doroti Santos,Índia,Bombas de Chocolate,28/07/2024,"$2,504.62",397.0,NaN
3281,Karina Machado,Índia,Mordidas 70% Cacau,23/05/2024,"$5,915.87",355.0,NaN

In [8]:


# valores vazios
# 2 tipos: linhas com valores vazios e colunas com muitos valores vazios
vendas_df = vendas_df.drop(columns="Data de Hoje")
vendas_df = vendas_df.dropna() # exclui linhas que têm algum valor vazio

# valores em formatação errada
# object -> textos
# float -> numeros com casa decimal
# datetime -> datas
vendas_df["Data"] = pd.to_datetime(vendas_df["Data"], dayfirst=True)
# Valor -> $5,320.00
vendas_df["Valor"] = vendas_df["Valor"].str.replace("$", "").str.replace(",", "")
vendas_df["Valor"] = vendas_df["Valor"].astype(float)


# valores duplicados
vendas_df = vendas_df.drop_duplicates()

# reset no indice da base de dados
vendas_df = vendas_df.reset_index(drop=True)

print(vendas_df.info()) # identificar problemas na base de dados
display(vendas_df)

<class 'pandas.DataFrame'>
RangeIndex: 3155 entries, 0 to 3154
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vendedor         3155 non-null   str
 1   País             3155 non-null   str
 2   Produto          3155 non-null   str
 3   Data             3155 non-null   datetime64[us]
 4   Valor            3155 non-null   float64
 5   Caixas Enviadas  3155 non-null   float64
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 148.0 KB
None

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,2022-01-04,5320.00,180.0
1,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,2022-07-07,4501.00,91.0
2,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,2022-04-27,12726.00,342.0
3,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,2022-02-24,13685.00,184.0
4,Vanderlei Teixeira,Índia,Salgadinho Suave e Sedoso,2022-06-06,5376.00,38.0
...,...,...,...,...,...,...
3150,Karina Machado,Austrália,Especiais Apimentados Finos,2024-05-17,5303.58,354.0
3151,João Rocha,EUA,Chocolate Branco,2024-06-07,7339.32,121.0
3152,Célio Bonfim,Canadá,Xarope de Chocolate Orgânico,2024-07-26,616.09,238.0
3153,Doroti Santos,Índia,Bombas de Chocolate,2024-07-28,2504.62,397.0
3154,Karina Machado,Índia,Mordidas 70% Cacau,2024-05-23,5915.87,355.0

In [9]:
display(vendas_df.describe()) # cria uma descrição estatística das colunas numéricas

                             Data         Valor  Caixas Enviadas
count                        3155   3155.000000      3155.000000
mean   2023-05-01 17:10:08.177496   6021.792041       164.105547
min           2022-01-03 00:00:00      7.000000         1.000000
25%           2022-06-30 00:00:00   2510.805000        71.000000
50%           2023-05-10 00:00:00   5220.800000       137.000000
75%           2024-03-01 12:00:00   8548.920000       232.000000
max           2024-08-31 00:00:00  26170.950000       778.000000
std                           NaN   4393.267909       123.288244

In [10]:
# feature engineering
vendas_df["Mes"] = vendas_df["Data"].dt.to_period("M")
# dt = datetime
vendas_df["Ano"] = vendas_df["Data"].dt.year
display(vendas_df)

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas,Mes,Ano
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,2022-01-04,5320.00,180.0,2022-01,2022
1,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,2022-07-07,4501.00,91.0,2022-07,2022
2,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,2022-04-27,12726.00,342.0,2022-04,2022
3,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,2022-02-24,13685.00,184.0,2022-02,2022
4,Vanderlei Teixeira,Índia,Salgadinho Suave e Sedoso,2022-06-06,5376.00,38.0,2022-06,2022
...,...,...,...,...,...,...,...,...
3150,Karina Machado,Austrália,Especiais Apimentados Finos,2024-05-17,5303.58,354.0,2024-05,2024
3151,João Rocha,EUA,Chocolate Branco,2024-06-07,7339.32,121.0,2024-06,2024
3152,Célio Bonfim,Canadá,Xarope de Chocolate Orgânico,2024-07-26,616.09,238.0,2024-07,2024
3153,Doroti Santos,Índia,Bombas de Chocolate,2024-07-28,2504.62,397.0,2024-07,2024
3154,Karina Machado,Índia,Mordidas 70% Cacau,2024-05-23,5915.87,355.0,2024-05,2024

In [ ]:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = "browser"

grafico = px.bar(vendas_mes, x=vendas_mes["Mes"].astype(str), y="Valor")
grafico.show()

In [17]:
# analise de volume e ticket medio anual
vendas_ano = vendas_df[["Ano", "Valor", "Caixas Enviadas"]]
vendas_ano = vendas_ano.groupby("Ano", as_index=False).sum()
vendas_ano["Ticket Medio"] = vendas_ano["Valor"] / vendas_ano["Caixas Enviadas"]

vendas_ano["% Crescimento Valor"] = vendas_ano["Valor"].pct_change()

display(vendas_ano.style.format({
    "Valor": "${:,.2f}",
    "Caixas Enviadas": "{:,.0f}",
    "Ticket Medio": "${:,.2f}",
    "% Crescimento Valor": "{:,.1%}",
}))